name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_bazel:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Run code generator
      run: ./MRA-codegen.py -e

    - name: Build and test with Bazel
      run: ./MRA-build.py -t

      # TODO: configure a cache?

  build_cmake:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Set up library dependencies
      run: |
        sudo apt-get install -y protobuf-compiler libspdlog-dev

    - name: Create build folder
      run: mkdir build

    - name: Build and test with Cmake
      run: ./MRA-build.py -t --cmake

