name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies which are not handled via bazel
      run: sudo apt-get install protobuf-compiler
      # TODO: the following dependencies are undesired/unexpected: protobuf-compiler

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Run code generator
      run: ./MRA-codegen.py -e

    - name: Build and test with Bazel
      run: ./MRA-build.py -t

      # TODO: add also cmake build steps here, or as separate action/yml
      # TODO: configure a cache

